<?php

namespace Database\Seeders;

use App\Models\Collection;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LegoSeeder extends Seeder
{
    public function run(): void
    {
        $collection = Collection::create([
            'name' => 'Lego',
            'available' => true,
        ]);

        DB::table('items')->insert([
            [
                'name' => 'lego3',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego3-1692309958.png',
                'a_red' => 139,
                'a_blue' => 131,
                'a_green' => 122,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 78,
                'ab_green' => 77,
                'ab_blue' => 77,
            ],
            [
                'name' => 'lego1',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego1-1692309960.png',
                'a_red' => 189,
                'a_blue' => 157,
                'a_green' => 165,
                'd_red' => 204,
                'd_blue' => 204,
                'd_green' => 204,
                'ab_red' => 223,
                'ab_green' => 219,
                'ab_blue' => 202,
            ],
            [
                'name' => 'lego2',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego2-1692309961.png',
                'a_red' => 189,
                'a_blue' => 157,
                'a_green' => 165,
                'd_red' => 204,
                'd_blue' => 204,
                'd_green' => 204,
                'ab_red' => 220,
                'ab_green' => 217,
                'ab_blue' => 198,
            ],
            [
                'name' => 'lego4',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego4-1692309962.png',
                'a_red' => 169,
                'a_blue' => 182,
                'a_green' => 173,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 107,
                'ab_green' => 107,
                'ab_blue' => 108,
            ],
            [
                'name' => 'lego5',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego5-1692309963.png',
                'a_red' => 166,
                'a_blue' => 149,
                'a_green' => 155,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 97,
                'ab_green' => 83,
                'ab_blue' => 72,
            ],
            [
                'name' => 'lego6',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego6-1692309965.png',
                'a_red' => 171,
                'a_blue' => 143,
                'a_green' => 158,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 129,
                'ab_green' => 119,
                'ab_blue' => 90,
            ],
            [
                'name' => 'lego7',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego7-1692309966.png',
                'a_red' => 148,
                'a_blue' => 76,
                'a_green' => 124,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 120,
                'ab_green' => 93,
                'ab_blue' => 56,
            ],
            [
                'name' => 'lego8',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego8-1692309967.png',
                'a_red' => 94,
                'a_blue' => 57,
                'a_green' => 74,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 92,
                'ab_green' => 85,
                'ab_blue' => 76,
            ],
            [
                'name' => 'lego9',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego9-1692309968.png',
                'a_red' => 64,
                'a_blue' => 118,
                'a_green' => 74,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 20,
                'ab_green' => 49,
                'ab_blue' => 124,
            ],
            [
                'name' => 'lego10',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego10-1692309969.png',
                'a_red' => 74,
                'a_blue' => 159,
                'a_green' => 125,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 62,
                'ab_green' => 131,
                'ab_blue' => 158,
            ],
            [
                'name' => 'lego11',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego11-1692309970.png',
                'a_red' => 77,
                'a_blue' => 57,
                'a_green' => 104,
                'd_red' => 51,
                'd_blue' => 0,
                'd_green' => 102,
                'ab_red' => 40,
                'ab_green' => 86,
                'ab_blue' => 43,
            ],
            [
                'name' => 'lego12',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego12-1692309971.png',
                'a_red' => 105,
                'a_blue' => 10,
                'a_green' => 91,
                'd_red' => 119,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 90,
                'ab_green' => 172,
                'ab_blue' => 58,
            ],
            [
                'name' => 'lego13',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego13-1692309971.png',
                'a_red' => 166,
                'a_blue' => 30,
                'a_green' => 122,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 199,
                'ab_green' => 221,
                'ab_blue' => 72,
            ],
            [
                'name' => 'lego14',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego14-1692309972.png',
                'a_red' => 199,
                'a_blue' => 66,
                'a_green' => 175,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 198,
                'ab_green' => 175,
                'ab_blue' => 61,
            ],
            [
                'name' => 'lego15',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego15-1692309973.png',
                'a_red' => 183,
                'a_blue' => 40,
                'a_green' => 102,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 186,
                'ab_green' => 87,
                'ab_blue' => 39,
            ],
            [
                'name' => 'lego16',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego16-1692309974.png',
                'a_red' => 173,
                'a_blue' => 20,
                'a_green' => 30,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 51,
                'ab_red' => 219,
                'ab_green' => 67,
                'ab_blue' => 45,
            ],
            [
                'name' => 'lego17',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego17-1692309975.png',
                'a_red' => 142,
                'a_blue' => 20,
                'a_green' => 40,
                'd_red' => 102,
                'd_blue' => 0,
                'd_green' => 51,
                'ab_red' => 134,
                'ab_green' => 34,
                'ab_blue' => 33,
            ],
            [
                'name' => 'lego18',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego18-1692309976.png',
                'a_red' => 168,
                'a_blue' => 106,
                'a_green' => 114,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 183,
                'ab_green' => 171,
                'ab_blue' => 162,
            ],
            [
                'name' => 'lego19',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego19-1692309977.png',
                'a_red' => 183,
                'a_blue' => 152,
                'a_green' => 136,
                'd_red' => 253,
                'd_blue' => 199,
                'd_green' => 173,
                'ab_red' => 205,
                'ab_green' => 155,
                'ab_blue' => 171,
            ],
            [
                'name' => 'lego20',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego20-1692309978.png',
                'a_red' => 162,
                'a_blue' => 111,
                'a_green' => 95,
                'd_red' => 253,
                'd_blue' => 199,
                'd_green' => 173,
                'ab_red' => 208,
                'ab_green' => 139,
                'ab_blue' => 178,
            ],
            [
                'name' => 'lego21',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego21-1692309979.png',
                'a_red' => 171,
                'a_blue' => 124,
                'a_green' => 93,
                'd_red' => 234,
                'd_blue' => 136,
                'd_green' => 76,
                'ab_red' => 180,
                'ab_green' => 74,
                'ab_blue' => 123,
            ],
            [
                'name' => 'lego22',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego22-1692309980.png',
                'a_red' => 125,
                'a_blue' => 37,
                'a_green' => 53,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 51,
                'ab_red' => 144,
                'ab_green' => 41,
                'ab_blue' => 78,
            ],
            [
                'name' => 'lego23',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego23-1692309980.png',
                'a_red' => 108,
                'a_blue' => 152,
                'a_green' => 101,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 68,
                'ab_green' => 68,
                'ab_blue' => 134,
            ],
            [
                'name' => 'lego24',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego24-1692309981.png',
                'a_red' => 108,
                'a_blue' => 152,
                'a_green' => 101,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 69,
                'ab_green' => 57,
                'ab_blue' => 135,
            ],
            [
                'name' => 'lego25',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego25-1692309982.png',
                'a_red' => 139,
                'a_blue' => 162,
                'a_green' => 132,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 154,
                'ab_green' => 131,
                'ab_blue' => 176,
            ],
            [
                'name' => 'lego26',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego26-1692309984.png',
                'a_red' => 129,
                'a_blue' => 152,
                'a_green' => 101,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 126,
                'ab_green' => 79,
                'ab_blue' => 141,
            ],
            [
                'name' => 'lego27',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego27-1692309985.png',
                'a_red' => 131,
                'a_blue' => 105,
                'a_green' => 48,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 113,
                'ab_green' => 38,
                'ab_blue' => 88,
            ],
            [
                'name' => 'lego28',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego28-1692309986.png',
                'a_red' => 115,
                'a_blue' => 108,
                'a_green' => 64,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 77,
                'ab_green' => 21,
                'ab_blue' => 77,
            ],
            [
                'name' => 'lego29',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego29-1692309987.png',
                'a_red' => 64,
                'a_blue' => 77,
                'a_green' => 33,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 45,
                'ab_green' => 25,
                'ab_blue' => 78,
            ],
            [
                'name' => 'lego30',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego30-1692309988.png',
                'a_red' => 151,
                'a_blue' => 86,
                'a_green' => 135,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 199,
                'ab_green' => 221,
                'ab_blue' => 140,
            ],
            [
                'name' => 'lego31',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego31-1692309989.png',
                'a_red' => 169,
                'a_blue' => 182,
                'a_green' => 173,
                'd_red' => 204,
                'd_blue' => 204,
                'd_green' => 204,
                'ab_red' => 188,
                'ab_green' => 216,
                'ab_blue' => 206,
            ],
            [
                'name' => 'lego32',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego32-1692309990.png',
                'a_red' => 74,
                'a_blue' => 159,
                'a_green' => 125,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 53,
                'ab_green' => 120,
                'ab_blue' => 120,
            ],
            [
                'name' => 'lego33',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego33-1692309991.png',
                'a_red' => 129,
                'a_blue' => 131,
                'a_green' => 142,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 91,
                'ab_green' => 117,
                'ab_blue' => 95,
            ],
            [
                'name' => 'lego34',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego34-1692309992.png',
                'a_red' => 118,
                'a_blue' => 121,
                'a_green' => 91,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 84,
                'ab_green' => 98,
                'ab_blue' => 117,
            ],
            [
                'name' => 'lego35',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego35-1692309993.png',
                'a_red' => 115,
                'a_blue' => 176,
                'a_green' => 129,
                'd_red' => 171,
                'd_blue' => 218,
                'd_green' => 188,
                'ab_red' => 120,
                'ab_green' => 159,
                'ab_blue' => 201,
            ],
            [
                'name' => 'lego36',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego36-1692309993.png',
                'a_red' => 94,
                'a_blue' => 149,
                'a_green' => 104,
                'd_red' => 102,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 77,
                'ab_green' => 116,
                'ab_blue' => 163,
            ],
            [
                'name' => 'lego37',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego37-1692309995.png',
                'a_red' => 94,
                'a_blue' => 149,
                'a_green' => 104,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 86,
                'ab_green' => 133,
                'ab_blue' => 157,
            ],
            [
                'name' => 'lego38',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego38-1692309995.png',
                'a_red' => 74,
                'a_blue' => 159,
                'a_green' => 125,
                'd_red' => 102,
                'd_blue' => 204,
                'd_green' => 204,
                'ab_red' => 68,
                'ab_green' => 144,
                'ab_blue' => 172,
            ],
            [
                'name' => 'lego39',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego39-1692309996.png',
                'a_red' => 43,
                'a_blue' => 169,
                'a_green' => 115,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 45,
                'ab_green' => 104,
                'ab_blue' => 163,
            ],
            [
                'name' => 'lego40',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego40-1692309997.png',
                'a_red' => 74,
                'a_blue' => 88,
                'a_green' => 43,
                'd_red' => 51,
                'd_blue' => 153,
                'd_green' => 51,
                'ab_red' => 21,
                'ab_green' => 50,
                'ab_blue' => 117,
            ],
            [
                'name' => 'lego41',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego41-1692309998.png',
                'a_red' => 105,
                'a_blue' => 16,
                'a_green' => 13,
                'd_red' => 0,
                'd_blue' => 0,
                'd_green' => 0,
                'ab_red' => 22,
                'ab_green' => 32,
                'ab_blue' => 46,
            ],
            [
                'name' => 'lego42',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego42-1692309999.png',
                'a_red' => 125,
                'a_blue' => 30,
                'a_green' => 142,
                'd_red' => 119,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 147,
                'ab_green' => 167,
                'ab_blue' => 69,
            ],
            [
                'name' => 'lego43',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego43-1692310000.png',
                'a_red' => 105,
                'a_blue' => 57,
                'a_green' => 94,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 105,
                'ab_green' => 106,
                'ab_blue' => 68,
            ],
            [
                'name' => 'lego44',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego44-1692310001.png',
                'a_red' => 98,
                'a_blue' => 98,
                'a_green' => 145,
                'd_red' => 119,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 71,
                'ab_green' => 141,
                'ab_blue' => 78,
            ],
            [
                'name' => 'lego46',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego46-1692310002.png',
                'a_red' => 94,
                'a_blue' => 47,
                'a_green' => 43,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 29,
                'ab_green' => 46,
                'ab_blue' => 36,
            ],
            [
                'name' => 'lego45',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego45-1692310003.png',
                'a_red' => 77,
                'a_blue' => 57,
                'a_green' => 104,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 46,
                'ab_green' => 102,
                'ab_blue' => 58,
            ],
            [
                'name' => 'lego47',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego47-1692310004.png',
                'a_red' => 178,
                'a_blue' => 66,
                'a_green' => 124,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 228,
                'ab_green' => 204,
                'ab_blue' => 130,
            ],
            [
                'name' => 'lego48',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego48-1692310005.png',
                'a_red' => 178,
                'a_blue' => 66,
                'a_green' => 124,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 230,
                'ab_green' => 212,
                'ab_blue' => 121,
            ],
            [
                'name' => 'lego49',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego49-1692310006.png',
                'a_red' => 183,
                'a_blue' => 40,
                'a_green' => 122,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 218,
                'ab_green' => 183,
                'ab_blue' => 72,
            ],
            [
                'name' => 'lego50',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego50-1692310006.png',
                'a_red' => 189,
                'a_blue' => 96,
                'a_green' => 155,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 220,
                'ab_green' => 182,
                'ab_blue' => 123,
            ],
            [
                'name' => 'lego51',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego51-1692310007.png',
                'a_red' => 183,
                'a_blue' => 40,
                'a_green' => 122,
                'd_red' => 255,
                'd_blue' => 51,
                'd_green' => 204,
                'ab_red' => 228,
                'ab_green' => 163,
                'ab_blue' => 62,
            ],
            [
                'name' => 'lego52',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego52-1692310008.png',
                'a_red' => 183,
                'a_blue' => 40,
                'a_green' => 122,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 214,
                'ab_green' => 130,
                'ab_blue' => 56,
            ],
            [
                'name' => 'lego53',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego53-1692310009.png',
                'a_red' => 183,
                'a_blue' => 40,
                'a_green' => 91,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 213,
                'ab_green' => 106,
                'ab_blue' => 51,
            ],
            [
                'name' => 'lego54',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego54-1692310010.png',
                'a_red' => 142,
                'a_blue' => 51,
                'a_green' => 81,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 127,
                'ab_green' => 67,
                'ab_blue' => 40,
            ],
            [
                'name' => 'lego55',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego55-1692310011.png',
                'a_red' => 168,
                'a_blue' => 86,
                'a_green' => 124,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 146,
                'ab_green' => 98,
                'ab_blue' => 62,
            ],
            [
                'name' => 'lego56',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego56-1692310012.png',
                'a_red' => 168,
                'a_blue' => 86,
                'a_green' => 124,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 181,
                'ab_green' => 119,
                'ab_blue' => 81,
            ],
            [
                'name' => 'lego57',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego57-1692310013.png',
                'a_red' => 158,
                'a_blue' => 76,
                'a_green' => 94,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 212,
                'ab_green' => 173,
                'ab_blue' => 142,
            ],
            [
                'name' => 'lego58',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego58-1692310014.png',
                'a_red' => 141,
                'a_blue' => 92,
                'a_green' => 127,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 182,
                'ab_green' => 163,
                'ab_blue' => 119,
            ],
            [
                'name' => 'lego59',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego59-1692310014.png',
                'a_red' => 141,
                'a_blue' => 92,
                'a_green' => 117,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 108,
                'ab_green' => 94,
                'ab_blue' => 71,
            ],
            [
                'name' => 'lego60',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego60-1692310015.png',
                'a_red' => 94,
                'a_blue' => 57,
                'a_green' => 74,
                'd_red' => 102,
                'd_blue' => 0,
                'd_green' => 51,
                'ab_red' => 58,
                'ab_green' => 38,
                'ab_blue' => 27,
            ],
            [
                'name' => 'lego61',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego61-1692310017.png',
                'a_red' => 84,
                'a_blue' => 26,
                'a_green' => 43,
                'd_red' => 102,
                'd_blue' => 0,
                'd_green' => 51,
                'ab_red' => 64,
                'ab_green' => 38,
                'ab_blue' => 28,
            ],
            [
                'name' => 'lego62',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego62-1692310018.png',
                'a_red' => 141,
                'a_blue' => 92,
                'a_green' => 117,
                'd_red' => 153,
                'd_blue' => 51,
                'd_green' => 102,
                'ab_red' => 119,
                'ab_green' => 85,
                'ab_blue' => 78,
            ],
            [
                'name' => 'lego63',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego63-1692310019.png',
                'a_red' => 163,
                'a_blue' => 30,
                'a_green' => 61,
                'd_red' => 204,
                'd_blue' => 51,
                'd_green' => 51,
                'ab_red' => 155,
                'ab_green' => 44,
                'ab_blue' => 38,
            ],
            [
                'name' => 'lego64',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego64-1692310020.png',
                'a_red' => 115,
                'a_blue' => 57,
                'a_green' => 74,
                'd_red' => 102,
                'd_blue' => 0,
                'd_green' => 51,
                'ab_red' => 79,
                'ab_green' => 32,
                'ab_blue' => 28,
            ],
            [
                'name' => 'lego65',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego65-1692310021.png',
                'a_red' => 168,
                'a_blue' => 86,
                'a_green' => 114,
                'd_red' => 231,
                'd_blue' => 177,
                'd_green' => 216,
                'ab_red' => 210,
                'ab_green' => 185,
                'ab_blue' => 135,
            ],
            [
                'name' => 'lego66',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego66-1692310022.png',
                'a_red' => 199,
                'a_blue' => 168,
                'a_green' => 186,
                'd_red' => 204,
                'd_blue' => 204,
                'd_green' => 204,
                'ab_red' => 216,
                'ab_green' => 210,
                'ab_blue' => 199,
            ],
            [
                'name' => 'lego67',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego67-1692310023.png',
                'a_red' => 149,
                'a_blue' => 141,
                'a_green' => 142,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 129,
                'ab_green' => 129,
                'ab_blue' => 128,
            ],
            [
                'name' => 'lego68',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego68-1692310025.png',
                'a_red' => 149,
                'a_blue' => 141,
                'a_green' => 142,
                'd_red' => 153,
                'd_blue' => 153,
                'd_green' => 153,
                'ab_red' => 117,
                'ab_green' => 118,
                'ab_blue' => 111,
            ],
            [
                'name' => 'lego69',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego69-1692310026.png',
                'a_red' => 94,
                'a_blue' => 57,
                'a_green' => 64,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 66,
                'ab_green' => 63,
                'ab_blue' => 56,
            ],
            [
                'name' => 'lego71',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego71-1692310027.png',
                'a_red' => 105,
                'a_blue' => 16,
                'a_green' => 13,
                'd_red' => 0,
                'd_blue' => 0,
                'd_green' => 0,
                'ab_red' => 20,
                'ab_green' => 19,
                'ab_blue' => 18,
            ],
            [
                'name' => 'lego70',
                'collection_id' => $collection->id,
                'popularity' => 1,
                'image_url' => 'https://matching-api-bucket.s3.eu-west-3.amazonaws.com/collections/4/items/lego70-1692310028.png',
                'a_red' => 94,
                'a_blue' => 47,
                'a_green' => 43,
                'd_red' => 66,
                'd_blue' => 83,
                'd_green' => 65,
                'ab_red' => 61,
                'ab_green' => 63,
                'ab_blue' => 63,
            ],
        ]);
    }
}
